// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package catalogdb

import (
	"context"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one

INSERT INTO products (name, description, currency, price_amount)
VALUES ($1, $2, $3, $4)
    RETURNING id, name, description, currency, price_amount, created_at, updated_at
`

type CreateProductParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Currency    string `json:"currency"`
	PriceAmount int64  `json:"price_amount"`
}

// internal/catalog/infra/postgres/queries/products.sql
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Currency,
		arg.PriceAmount,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Currency,
		&i.PriceAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, description, currency, price_amount, created_at, updated_at
FROM products
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Currency,
		&i.PriceAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, description, currency, price_amount, created_at, updated_at
FROM products
WHERE ($1 = '' OR name ILIKE '%' || $1 || '%')
  AND ($2 = false OR id < $3)
ORDER BY id DESC
    LIMIT $4
`

type ListProductsParams struct {
	Query     interface{} `json:"query"`
	UseCursor interface{} `json:"use_cursor"`
	Cursor    uuid.UUID   `json:"cursor"`
	PageLimit int32       `json:"page_limit"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts,
		arg.Query,
		arg.UseCursor,
		arg.Cursor,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Currency,
			&i.PriceAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
