// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package orderdb

import (
	"time"

	"github.com/google/uuid"
)

type Order struct {
	ID             uuid.UUID `json:"id"`
	UserID         string    `json:"user_id"`
	Status         string    `json:"status"`
	Currency       string    `json:"currency"`
	SubtotalAmount int64     `json:"subtotal_amount"`
	ShippingAmount int64     `json:"shipping_amount"`
	TotalAmount    int64     `json:"total_amount"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type OrderItem struct {
	ID              uuid.UUID `json:"id"`
	OrderID         uuid.UUID `json:"order_id"`
	ProductID       uuid.UUID `json:"product_id"`
	Name            string    `json:"name"`
	UnitAmount      int64     `json:"unit_amount"`
	Quantity        int32     `json:"quantity"`
	LineTotalAmount int64     `json:"line_total_amount"`
}
