// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package orderdb

import (
	"context"

	"github.com/google/uuid"
)

const addOrderItem = `-- name: AddOrderItem :one
INSERT INTO order_items (
    id,
    order_id,
    product_id,
    name,
    unit_amount,
    quantity,
    line_total_amount
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
         )
RETURNING id, order_id, product_id, name, unit_amount, quantity, line_total_amount
`

type AddOrderItemParams struct {
	ID              uuid.UUID `json:"id"`
	OrderID         uuid.UUID `json:"order_id"`
	ProductID       uuid.UUID `json:"product_id"`
	Name            string    `json:"name"`
	UnitAmount      int64     `json:"unit_amount"`
	Quantity        int32     `json:"quantity"`
	LineTotalAmount int64     `json:"line_total_amount"`
}

func (q *Queries) AddOrderItem(ctx context.Context, arg AddOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, addOrderItem,
		arg.ID,
		arg.OrderID,
		arg.ProductID,
		arg.Name,
		arg.UnitAmount,
		arg.Quantity,
		arg.LineTotalAmount,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Name,
		&i.UnitAmount,
		&i.Quantity,
		&i.LineTotalAmount,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    id,
    user_id,
    status,
    currency,
    subtotal_amount,
    shipping_amount,
    total_amount
) VALUES (
     $1, $2, $3, $4,
$5, $6, $7
 ) RETURNING id, user_id, status, currency, subtotal_amount, shipping_amount, total_amount, created_at, updated_at
`

type CreateOrderParams struct {
	ID             uuid.UUID `json:"id"`
	UserID         string    `json:"user_id"`
	Status         string    `json:"status"`
	Currency       string    `json:"currency"`
	SubtotalAmount int64     `json:"subtotal_amount"`
	ShippingAmount int64     `json:"shipping_amount"`
	TotalAmount    int64     `json:"total_amount"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.Status,
		arg.Currency,
		arg.SubtotalAmount,
		arg.ShippingAmount,
		arg.TotalAmount,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.SubtotalAmount,
		&i.ShippingAmount,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderById = `-- name: GetOrderById :one
SELECT id, user_id, status, currency, subtotal_amount, shipping_amount, total_amount, created_at, updated_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrderById(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderById, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.SubtotalAmount,
		&i.ShippingAmount,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrderByUserId = `-- name: ListOrderByUserId :many
SELECT id, user_id, status, currency, subtotal_amount, shipping_amount, total_amount, created_at, updated_at FROM orders WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListOrderByUserIdParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListOrderByUserId(ctx context.Context, arg ListOrderByUserIdParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrderByUserId, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Currency,
			&i.SubtotalAmount,
			&i.ShippingAmount,
			&i.TotalAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItem = `-- name: ListOrderItem :many
SELECT id, order_id, product_id, name, unit_amount, quantity, line_total_amount FROM order_items WHERE order_id = $1
`

func (q *Queries) ListOrderItem(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItem, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Name,
			&i.UnitAmount,
			&i.Quantity,
			&i.LineTotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
