// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cart.sql

package cartgdb

import (
	"context"

	"github.com/google/uuid"
)

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items
WHERE cart_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, cartID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearCart, cartID)
	return err
}

const createActiveCart = `-- name: CreateActiveCart :one
INSERT INTO carts (user_id, status)
VALUES ($1, 'ACTIVE')
    RETURNING id, user_id, status, created_at, updated_at
`

func (q *Queries) CreateActiveCart(ctx context.Context, userID uuid.UUID) (Cart, error) {
	row := q.db.QueryRowContext(ctx, createActiveCart, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveCartByUserID = `-- name: GetActiveCartByUserID :one
SELECT id, user_id, status, created_at, updated_at FROM carts
WHERE user_id = $1 AND status = 'ACTIVE'
    LIMIT 1
`

func (q *Queries) GetActiveCartByUserID(ctx context.Context, userID uuid.UUID) (Cart, error) {
	row := q.db.QueryRowContext(ctx, getActiveCartByUserID, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCartItems = `-- name: ListCartItems :many
SELECT id, cart_id, product_id, quantity, created_at, updated_at FROM cart_items
WHERE cart_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListCartItems(ctx context.Context, cartID uuid.UUID) ([]CartItem, error) {
	rows, err := q.db.QueryContext(ctx, listCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CartItem
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeItem = `-- name: RemoveItem :exec
DELETE FROM cart_items
WHERE cart_id = $1 AND product_id = $2
`

type RemoveItemParams struct {
	CartID    uuid.UUID `json:"cart_id"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) RemoveItem(ctx context.Context, arg RemoveItemParams) error {
	_, err := q.db.ExecContext(ctx, removeItem, arg.CartID, arg.ProductID)
	return err
}

const setItemQuantity = `-- name: SetItemQuantity :one
UPDATE cart_items
SET quantity = $3, updated_at = now()
WHERE cart_id = $1 AND product_id = $2
    RETURNING id, cart_id, product_id, quantity, created_at, updated_at
`

type SetItemQuantityParams struct {
	CartID    uuid.UUID `json:"cart_id"`
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int32     `json:"quantity"`
}

func (q *Queries) SetItemQuantity(ctx context.Context, arg SetItemQuantityParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, setItemQuantity, arg.CartID, arg.ProductID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchCartUpdatedAt = `-- name: TouchCartUpdatedAt :exec
UPDATE carts SET updated_at = now()
WHERE id = $1
`

func (q *Queries) TouchCartUpdatedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, touchCartUpdatedAt, id)
	return err
}

const upsertAddItemIncrement = `-- name: UpsertAddItemIncrement :one
INSERT INTO cart_items (cart_id, product_id, quantity)
VALUES ($1, $2, $3)
    ON CONFLICT (cart_id, product_id)
DO UPDATE SET
    quantity   = cart_items.quantity + EXCLUDED.quantity,
           updated_at = now()
           RETURNING id, cart_id, product_id, quantity, created_at, updated_at
`

type UpsertAddItemIncrementParams struct {
	CartID    uuid.UUID `json:"cart_id"`
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int32     `json:"quantity"`
}

func (q *Queries) UpsertAddItemIncrement(ctx context.Context, arg UpsertAddItemIncrementParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, upsertAddItemIncrement, arg.CartID, arg.ProductID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
